version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9.14-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    #    volumes:
    #      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - internal

networks:
  internal:
